from ui_avatars.generator import avatars


def avatar_url(
    *,
    name: str | None = None,
    email: str | None = None,
    alpha: float | None = None,
    background: str | None = None,
    bold: bool | None = None,
    color: str | None = None,
    font_color: str | None = None,
    font_size: float | None = None,
    format: str | None = None,
    host: str | None = None,
    length: int | None = None,
    mask: str | None = None,
    proxy: str | None = None,
    region: str | None = None,
    rounded: bool | None = None,
    size: int | None = None,
    source: str | None = None,
    uppercase: bool | None = None,
) -> str:
    return avatars.build(
        name=name,
        email=email,
        alpha=alpha,
        background=background,
        bold=bold,
        color=color,
        font_color=font_color,
        font_size=font_size,
        format=format,
        host=host,
        length=length,
        mask=mask,
        proxy=proxy,
        region=region,
        rounded=rounded,
        size=size,
        source=source,
        uppercase=uppercase,
    )
